#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MEDCALC ECG V25 · SIGNAL-LEVEL VISUAL MATCHER + EVIDENCE FUSION
===============================================================

The word "visual" here means morphology of the digitized ECG waveform, not
pixel-level screenshot similarity. This is intentional: once V23.1 has
calibrated the ECG into mV vs seconds, comparing signals is much more robust
to paper color, grid, JPEG compression, rotation, cropping, and background.

V25 compares:
  A) V23.1 objective measurements,
  B) V24 literature-rule results,
  C) lead-by-lead waveform morphology against ORIGINAL synthetic atlas
     prototypes generated by ecg_v25_visual_atlas.py.

A visual match NEVER overrides a negative/unsafe literature rule.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional
import json
import math

import numpy as np
from scipy.signal import resample

import ecg_v24_criteria_engine as v24
from ecg_v25_visual_atlas import (
    ATLAS, LEADS, FS, BEAT_START, BEAT_END, generate_beat,
)

VERSION = "V25.0-VISUAL-FUSION"

def _finite(x):
    try:
        if x is None:
            return None
        y = float(x)
        return y if np.isfinite(y) else None
    except Exception:
        return None

def _z(x):
    x = np.asarray(x, float)
    med = float(np.median(x))
    scale = float(np.median(np.abs(x-med))*1.4826)
    if not np.isfinite(scale) or scale < 1e-6:
        scale = float(np.std(x))
    if not np.isfinite(scale) or scale < 1e-6:
        scale = 1.0
    return (x-med)/scale

def _corr(a, b):
    a = np.asarray(a,float); b=np.asarray(b,float)
    if len(a)!=len(b) or len(a)<4:
        return None
    a=a-np.mean(a); b=b-np.mean(b)
    da=float(np.linalg.norm(a)); db=float(np.linalg.norm(b))
    if da<1e-9 or db<1e-9:
        return None
    return float(np.dot(a,b)/(da*db))

def _score_corr(c):
    if c is None or not np.isfinite(c):
        return None
    # Preserve penalty for anticorrelation, map [-1,1] -> [0,1].
    return float(np.clip((c+1.0)/2.0, 0.0, 1.0))

def _best_shift_corr(a, b, max_shift_samples):
    a=np.asarray(a,float); b=np.asarray(b,float)
    best=None; best_shift=0
    for s in range(-max_shift_samples, max_shift_samples+1):
        if s<0:
            aa=a[-s:]; bb=b[:len(b)+s]
        elif s>0:
            aa=a[:-s]; bb=b[s:]
        else:
            aa=a; bb=b
        if len(aa)<10: continue
        c=_corr(aa,bb)
        if c is not None and (best is None or c>best):
            best=c; best_shift=s
    return best,best_shift

def _segment_idx(t, a, b):
    return np.where((t>=a)&(t<=b))[0]

def extract_patient_median_beats(
    signals: dict[str, dict[str, Any]],
    measurements: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    """
    Extract a robust median beat around each lead's detected R event.
    Window is exactly the same duration as the digital atlas beat.
    """
    out={}
    n_target=int(round((BEAT_END-BEAT_START)*FS))
    target_t=np.arange(n_target,dtype=float)/FS+BEAT_START

    for lead in LEADS:
        rec=signals.get(lead)
        if rec is None:
            out[lead]={"reliable":False,"reason":"MISSING_LEAD"}
            continue
        x=v24._interp_invalid(rec["signal"], rec["valid"])
        if x is None:
            out[lead]={"reliable":False,"reason":"INVALID_SIGNAL"}
            continue
        fs=float(rec.get("fs",FS))
        filt=v24._lowpass(x,fs,40.0)
        det=v24._detect_r_and_waves(filt,fs)
        r=np.asarray(det.get("r",[]),dtype=int)
        beats=[]
        pre=int(round(abs(BEAT_START)*fs))
        post=int(round(BEAT_END*fs))
        for rp in r:
            a=int(rp-pre); b=int(rp+post)
            if a<0 or b>len(filt) or b-a<50: continue
            seg=filt[a:b].astype(float)
            # Baseline from far pre-QRS zone.
            n0=max(4,int(round(.080*fs)))
            base=float(np.median(seg[:n0]))
            seg=seg-base
            if len(seg)!=n_target:
                seg=resample(seg,n_target)
            beats.append(seg)
        if len(beats)<2:
            out[lead]={"reliable":False,"reason":"TOO_FEW_BEATS","n_beats":len(beats)}
            continue
        arr=np.vstack(beats)
        med=np.median(arr,axis=0)
        mad=np.median(np.abs(arr-med),axis=0)
        p2p=float(np.max(med)-np.min(med))
        out[lead]={
            "reliable":True,
            "time":target_t,
            "beat":med.astype(np.float32),
            "beat_mad_median":float(np.median(mad)),
            "n_beats":len(beats),
            "peak_to_peak_mV":p2p,
            "detection_method":det.get("method"),
        }
    return out

def _window_shape(patient, template, t, a, b, max_shift_ms=20.0):
    idx=_segment_idx(t,a,b)
    if len(idx)<8: return None
    pa=_z(patient[idx]); tb=_z(template[idx])
    ms=int(round(max_shift_ms/1000.0*FS))
    c,shift=_best_shift_corr(pa,tb,ms)
    if c is None: return None
    # Derivative agreement captures notching/slurring/terminal direction.
    dc,_=_best_shift_corr(np.gradient(pa),np.gradient(tb),ms)
    cs=_score_corr(c); ds=_score_corr(dc)
    return {
        "correlation":c,
        "derivative_correlation":dc,
        "shape_score":float(0.72*cs+0.28*ds),
        "best_shift_ms":float(shift/FS*1000.0),
    }

def compare_lead(patient_beat, template_beat, t, amplitude_weight=.15):
    windows={
        "P":(-.25,-.075,.12),
        "QRS":(-.070,.115,.48),
        "ST_T":(.070,.50,.40),
    }
    pieces={}
    scores=[]; weights=[]
    for name,(a,b,w) in windows.items():
        s=_window_shape(patient_beat,template_beat,t,a,b)
        pieces[name]=s
        if s is not None:
            scores.append(s["shape_score"]); weights.append(w)
    if not scores:
        return {"reliable":False,"reason":"NO_COMPARABLE_WINDOWS"}
    shape=float(np.average(scores,weights=weights))
    pp=float(np.ptp(patient_beat))
    tt=float(np.ptp(template_beat))
    if pp<=1e-6 or tt<=1e-6:
        amp=None
    else:
        amp=float(np.exp(-abs(math.log((pp+1e-6)/(tt+1e-6)))))
    if amp is None:
        total=shape
    else:
        total=(1-amplitude_weight)*shape+amplitude_weight*amp
    return {
        "reliable":True,
        "visual_score":float(np.clip(total,0,1)),
        "shape_score":shape,
        "amplitude_score":amp,
        "patient_peak_to_peak_mV":pp,
        "template_peak_to_peak_mV":tt,
        "windows":pieces,
    }

def visual_pattern_score(
    pattern_id: str,
    patient_beats: dict[str, dict[str, Any]],
    v24_result: dict[str, Any],
) -> dict[str, Any]:
    cfg=ATLAS[pattern_id]
    mode=cfg.get("visual_mode","beat")

    # Rhythm patterns use visually motivated rhythm/P evidence from V24 because
    # direct beat-shape matching is not meaningful when the defining feature is
    # beat-to-beat irregularity or atrial periodicity.
    if mode=="rhythm_feature":
        interp=((v24_result.get("interpretation") or {}))
        rules={r.get("rule_id"):r for r in interp.get("rules",[])}
        rid=cfg.get("v24_rules",[None])[0]
        r=rules.get(rid) or {}
        status=r.get("status")
        if status=="POSITIVE": score=.90
        elif status=="NEGATIVE": score=.15
        elif status=="CONFOUNDED": score=.35
        else: score=.50
        return {
            "visual_score":score,
            "coverage":1.0,
            "mode":"RHYTHM_MORPHOLOGY_FEATURES",
            "lead_scores":{},
            "note":"Rhythm visual evidence uses RR/P/atrial periodicity features rather than single-beat image correlation.",
        }

    amp_weight=.34 if mode=="beat_amplitude" else .15
    lead_scores={}
    vals=[]; wts=[]
    key=set(cfg.get("key_leads") or LEADS)
    for lead in cfg.get("key_leads") or LEADS:
        p=patient_beats.get(lead) or {}
        if not p.get("reliable"): continue
        t,tmpl=generate_beat(pattern_id,lead,FS)
        comp=compare_lead(np.asarray(p["beat"],float),np.asarray(tmpl,float),t,amplitude_weight=amp_weight)
        lead_scores[lead]=comp
        if comp.get("reliable"):
            vals.append(comp["visual_score"])
            # All key leads equal by default; registry can later add weights.
            wts.append(1.0)
    coverage=len(vals)/max(1,len(cfg.get("key_leads") or LEADS))
    score=float(np.average(vals,weights=wts)) if vals else None
    # Mild coverage penalty; do not manufacture confidence from one lead.
    if score is not None:
        score=float(score*(0.70+0.30*coverage))
    return {
        "visual_score":score,
        "coverage":coverage,
        "mode":"DIGITIZED_WAVEFORM_MORPHOLOGY",
        "lead_scores":lead_scores,
    }

def _measurement_constraint_score(
    constraints: dict[str, list[float]],
    measurements: dict[str, Any],
) -> dict[str, Any]:
    if not constraints:
        return {"score":None,"details":[]}
    vals=[]; details=[]
    for key,bounds in constraints.items():
        v=_finite(measurements.get(key))
        lo=float(bounds[0]); hi=float(bounds[1])
        if v is None:
            details.append({"key":key,"value":None,"status":"MISSING","score":None})
            continue
        if lo<=v<=hi:
            s=1.0; status="PASS"
        else:
            # Smooth falloff outside the interval, scale adapted to interval.
            scale=max(10.0,(hi-lo)*.30)
            dist=(lo-v) if v<lo else (v-hi)
            s=float(np.exp(-abs(dist)/scale))
            status="OUTSIDE"
        vals.append(s)
        details.append({"key":key,"value":v,"bounds":[lo,hi],"status":status,"score":s})
    return {"score":float(np.mean(vals)) if vals else None,"details":details}

def _criteria_score(pattern_id: str, v24_result: dict[str, Any]) -> dict[str, Any]:
    cfg=ATLAS[pattern_id]
    interp=v24_result.get("interpretation") or {}
    rules={r.get("rule_id"):r for r in interp.get("rules",[])}
    vals=[]; details=[]
    map_score={"POSITIVE":1.0,"NEGATIVE":0.0,"CONFOUNDED":.35,"NOT_ASSESSABLE":None}
    for rid in cfg.get("v24_rules",[]):
        r=rules.get(rid)
        if r is None:
            details.append({"rule_id":rid,"status":"MISSING","score":None}); continue
        status=r.get("status")
        s=map_score.get(status)
        if s is not None: vals.append(s)
        details.append({"rule_id":rid,"status":status,"score":s,"label":r.get("label")})
    return {"score":float(np.mean(vals)) if vals else None,"details":details}

def _combine_scores(criteria,visual,measurement):
    parts=[]; weights=[]
    if criteria is not None:
        parts.append(criteria); weights.append(.45)
    if visual is not None:
        parts.append(visual); weights.append(.35)
    if measurement is not None:
        parts.append(measurement); weights.append(.20)
    if not parts: return None
    return float(np.average(parts,weights=weights))

def _fusion_status(criteria,visual,fusion,coverage):
    if fusion is None:
        return "NO_VALORABLE"
    if criteria is not None and criteria>=.95:
        if visual is not None and coverage>=.50 and visual>=.72 and fusion>=.75:
            return "CONCORDANT_HIGH"
        if visual is not None and coverage>=.35 and visual>=.56 and fusion>=.63:
            return "CONCORDANT_MODERATE"
        return "CRITERIA_POSITIVE_VISUAL_DISCORDANT"
    if visual is not None and coverage>=.50 and visual>=.78:
        if criteria is None:
            return "VISUAL_ONLY_NO_RULE"
        if criteria<=.20:
            return "VISUAL_MATCH_WITHOUT_CRITERIA"
    if criteria is not None and criteria<=.20 and fusion<.60:
        return "NOT_SUPPORTED"
    return "INDETERMINATE"

def rank_visual_atlas(
    zip_path: str | Path,
    age_years: Optional[float]=None,
    sex: Optional[str]=None,
) -> dict[str, Any]:
    manifest,signals=v24.load_v23_zip(zip_path)
    measurements=manifest.get("objective_measurements") or {}
    v24_result=v24.interpret_v23_zip(zip_path,age_years=age_years,sex=sex)
    if v24_result.get("status")!="PASS":
        return {
            "version":VERSION,"status":"NO_VALORABLE",
            "reason":"V24_NOT_INTERPRETABLE","v24":v24_result
        }

    beats=extract_patient_median_beats(signals,measurements)
    matches=[]
    for pid,cfg in ATLAS.items():
        vis=visual_pattern_score(pid,beats,v24_result)
        cri=_criteria_score(pid,v24_result)
        mea=_measurement_constraint_score(cfg.get("measurement_constraints") or {},measurements)
        fusion=_combine_scores(cri["score"],vis["visual_score"],mea["score"])
        status=_fusion_status(cri["score"],vis["visual_score"],fusion,vis["coverage"])
        matches.append({
            "pattern_id":pid,
            "name":cfg["name"],
            "family":cfg["family"],
            "fusion_status":status,
            "fusion_score":fusion,
            "visual_score":vis["visual_score"],
            "visual_coverage":vis["coverage"],
            "visual_mode":vis["mode"],
            "criteria_score":cri["score"],
            "measurement_score":mea["score"],
            "criteria_details":cri["details"],
            "measurement_details":mea["details"],
            "lead_scores":vis.get("lead_scores",{}),
            "criteria_summary":cfg.get("criteria_summary",[]),
            "sources":cfg.get("sources",[]),
        })
    matches.sort(key=lambda x:(-1 if x["fusion_score"] is None else x["fusion_score"]),reverse=True)

    concordant=[
        m for m in matches
        if m["fusion_status"] in {"CONCORDANT_HIGH","CONCORDANT_MODERATE"}
    ]
    discordant=[
        m for m in matches
        if m["fusion_status"] in {"CRITERIA_POSITIVE_VISUAL_DISCORDANT","VISUAL_MATCH_WITHOUT_CRITERIA"}
    ]

    return {
        "version":VERSION,
        "status":"PASS",
        "source_file":manifest.get("source_file"),
        "measurements_v23_1":measurements,
        "v24":v24_result,
        "patient_beats":beats,
        "matches":matches,
        "concordant_matches":concordant,
        "discordant_matches":discordant,
        "interpretation_policy":{
            "visual_alone_can_diagnose":False,
            "v24_rule_required_for_concordant_support":True,
            "description":"Visual morphology is confirmatory/supportive; explicit literature criteria remain primary.",
        }
    }

def render_match_overlay(
    result: dict[str,Any],
    pattern_id: str,
    out_path: str | Path,
    max_leads: int=6,
):
    """
    Single-axes stacked overlay: patient median beat vs synthetic reference.
    Uses matplotlib default line colors to keep the artifact neutral.
    """
    import matplotlib.pyplot as plt
    matches={m["pattern_id"]:m for m in result.get("matches",[])}
    if pattern_id not in matches:
        raise KeyError(pattern_id)
    cfg=ATLAS[pattern_id]
    beats=result.get("patient_beats") or {}
    leads=[
        l for l in cfg.get("key_leads",LEADS)
        if (beats.get(l) or {}).get("reliable")
    ][:max_leads]
    if not leads:
        raise RuntimeError("No reliable leads for overlay")
    t=np.arange(int(round((BEAT_END-BEAT_START)*FS)))/FS+BEAT_START
    offsets=np.arange(len(leads))[::-1]*3.0
    fig=plt.figure(figsize=(11,2.1+1.1*len(leads)))
    ax=fig.add_subplot(111)
    for i,lead in enumerate(leads):
        patient=np.asarray(beats[lead]["beat"],float)
        _,tmpl=generate_beat(pattern_id,lead,FS)
        # Normalize template amplitude to patient's robust p2p only for display.
        pp=float(np.ptp(patient)); tp=float(np.ptp(tmpl))
        display_tmpl=tmpl*(pp/tp) if pp>1e-6 and tp>1e-6 else tmpl
        ax.plot(t,patient+offsets[i],label="Paciente" if i==0 else None)
        ax.plot(t,display_tmpl+offsets[i],label="Referencia sintética" if i==0 else None)
        ax.text(BEAT_START-.035,offsets[i],lead,ha="right",va="center",fontsize=8)
    ax.set_xlim(BEAT_START-.07,BEAT_END)
    ax.set_xlabel("Tiempo respecto del QRS (s)")
    ax.set_ylabel("Derivaciones apiladas")
    ax.set_title(
        f"MEDCALC V25 · paciente vs atlas · {cfg['name']} · "
        f"score={matches[pattern_id].get('visual_score') if matches[pattern_id].get('visual_score') is not None else 'NV'}"
    )
    ax.grid(True,linewidth=.4,alpha=.35)
    ax.legend()
    fig.tight_layout()
    out_path=Path(out_path)
    out_path.parent.mkdir(parents=True,exist_ok=True)
    fig.savefig(out_path,dpi=150)
    plt.close(fig)
    return out_path

def save_result(result: dict[str,Any], path: str | Path):
    def sanitize(obj):
        if isinstance(obj,np.ndarray): return obj.tolist()
        if isinstance(obj,np.generic): return obj.item()
        if isinstance(obj,dict): return {k:sanitize(v) for k,v in obj.items()}
        if isinstance(obj,list): return [sanitize(v) for v in obj]
        return obj
    path=Path(path)
    path.write_text(json.dumps(sanitize(result),indent=2,ensure_ascii=False),encoding="utf-8")
    return path

if __name__=="__main__":
    import argparse
    p=argparse.ArgumentParser()
    p.add_argument("zip")
    p.add_argument("--age",type=float,default=None)
    p.add_argument("--sex",default=None)
    p.add_argument("--out",default=None)
    a=p.parse_args()
    r=rank_visual_atlas(a.zip,a.age,a.sex)
    out=a.out or str(Path(a.zip).with_suffix(""))+"__V25_VISUAL.json"
    save_result(r,out)
    print("="*100)
    print("MEDCALC ECG V25 · VISUAL FUSION")
    print("="*100)
    for m in r.get("matches",[])[:8]:
        print(
            m["pattern_id"],
            "fusion=",None if m["fusion_score"] is None else round(m["fusion_score"],3),
            "visual=",None if m["visual_score"] is None else round(m["visual_score"],3),
            "criteria=",m["criteria_score"],
            m["fusion_status"],
        )
    print("JSON:",out)
